### ISSUE TITLE
Control rods do not shut off reactor

### ISSUE THREAD

**Issue by zzBuilderzz** [halvors/Quantum#16]
I have put 4 control rods direct adjacent to the reactor cell and yet it still will not turn off. If this supposed to do exactly as Atomic Science did in 1.6.4 then this is a bug. In Atomic Science one control rod is enough to turn the reactor completely off. As of right now all that one control does is keep the reactor from going above a certain temp.

**Comment by halvors** [comment]
@zzBuilderzz I agree that this doesn't make sense. But i'm unsure if control rods shuts down the reactor completly, i think there should more effective to have 4 than just 1. But indeed atleast slow it a lot more down than it is now. Maybe so that water keeps around boiling point? But generates next to zero energy?

**Comment by zzBuilderzz** [comment]
that would make much more sense to have them really slow down the reaction but not completely shut it down (as that's what control rods do in irl)

**Comment by halvors** [comment]
@zzBuilderzz Yeah. I will look into fixing that :)

**Comment by halvors** [comment]
@zzBuilderzz Should be fixed in e86b750a635a068713d9a10115b14fcea96a06cc, please try out the new build and see if it's solves the issue for you :)

**Comment by halvors** [comment]
Closing this, fix commited.
