### ISSUE TITLE
Reactor cells do not connect vertically anymore.

### ISSUE THREAD

**Issue by creeperCuller** [halvors/Quantum#17]
In the original mod, as well as early version of this mod, the reactor cells would connect vertically and share an inventory across all connected cells, but this no longer happens. Is there any intention to bring this back?

**Comment by halvors** [comment]
@creeperCuller Maybe eventually when the the mod is more stable. The reason it's not implemented is because of buggy behaviour. I'll need a complete redesign from calclavias version anyway, the reactor cell towers was not working as they whould.

* It did share the inventory, but the inventory did only have room for 1 fuel rod at the time.
* There was no actual functional benefit of stacking the cells.

So think you'll close this issue for now, as this is not an actual bug :)

But thank you very much for pointing this out!
