### ISSUE TITLE
Will fission lead to the disappearance of water?

### ISSUE THREAD

**Issue by ZHENGLOC** [halvors/Quantum#30]
After the fission reactor runs for a period of time, the water source will disappear.
https://i.imgur.com/vFHVO4K.png
https://i.imgur.com/rBsmpob.png

**Comment by halvors** [comment]
Game version 1.7.10?

**Comment by Njet75** [comment]
Can confirm it happens with latest build nuclearphysics-1.12.2-0.1.34.jar

**Comment by halvors** [comment]
@Njet75 Do you have a turbine or gas funnel over the water block that is despawning? The way this is supposed to work is that in uncontrolled enviroment like plasma running wild, water blocks should boil, also in reactor if no turbine/gas funnel over it.

@ZHENGLOC This is indeed a bug in 1.7.10, but it should work just fine on 1.10+.

To both of you, to clearify this, you have to have a turbine or gas funnel over water blocks that is part of a reactor, otherwise they will boil away eventually.

There is also an option in the mod configuration called "enableBoilingOfWaterBlocks" that is true by default but can be disabled to prevent this behaviour.
